USE db_fitracking;
DROP TABLE IF EXISTS USUARIS;
CREATE TABLE USUARIS (
    ID INT NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(30) DEFAULT NULL,
    CONTRA VARCHAR(30) DEFAULT NULL,
    NOM VARCHAR(30) DEFAULT NULL,
    EDAT INT DEFAULT NULL,
    PES FLOAT DEFAULT NULL,
    ALTURA FLOAT DEFAULT NULL,
    ACTIVITATFISICA VARCHAR(30) DEFAULT NULL,
    CONSUMAIGUA VARCHAR(30) DEFAULT NULL,
    HORASSUENO FLOAT DEFAULT NULL,
    NIVELESTRES FLOAT DEFAULT NULL,
    ALERGIAS JSON DEFAULT NULL,
    PREFERENCIESDIETA JSON DEFAULT NULL,
    OBJECTIUS JSON DEFAULT NULL,
    PRIMARY KEY (ID));

DROP TABLE IF EXISTS EXERCICIS;
CREATE TABLE EXERCICIS (
    ID INT NOT NULL AUTO_INCREMENT,
	NOM VARCHAR(50) DEFAULT NULL,
    DESCRIPCIO VARCHAR(200) DEFAULT NULL,
    REPETICIONS VARCHAR(70) DEFAULT NULL,
    DURACIO FLOAT DEFAULT NULL,
    DESCANS FLOAT DEFAULT NULL,
    DIFICULTAT VARCHAR(30) DEFAULT NULL,
	CATEGORIA VARCHAR(30) DEFAULT NULL,
    IMATGE VARCHAR(220) DEFAULT NULL,
    PRIMARY KEY (ID));

DROP TABLE IF EXISTS RUTINA_DIA_SETMANA;
CREATE TABLE RUTINA_DIA_SETMANA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    dia_setmana VARCHAR(20) NOT NULL UNIQUE
);

DROP TABLE IF EXISTS USUARI_RUTINA_EXERCICIS;
CREATE TABLE USUARI_RUTINA_EXERCICIS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuari_id INT NOT NULL,
    rutina_dia_id INT NOT NULL,
    exercici_id INT NOT NULL,
    exercici_completat BOOLEAN DEFAULT FALSE,
	objectiu_exercici  VARCHAR(200) DEFAULT NULL,
    FOREIGN KEY (usuari_id) REFERENCES usuaris(id) ON DELETE CASCADE,
    FOREIGN KEY (rutina_dia_id) REFERENCES rutina_dia_setmana(id),
    FOREIGN KEY (exercici_id) REFERENCES exercicis(id)
);
