USE fitracking_bdd;
DELETE FROM alimento;
ALTER TABLE alimento AUTO_INCREMENT = 1;
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Arroz', 100, 130);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Pollo', 100, 165);  -- Calorías por 100g de pechuga de pollo
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Pasta', 100, 350);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Tomate', 100, 18);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Lechuga', 100, 15);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Papa', 100, 77);  -- Calorías por 100g de patata cocida
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Carne de res', 100, 250);  -- Calorías por 100g de carne magra
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Manzana', 100, 52);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Leche', 100, 61);  -- Calorías por 100g de leche entera
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Huevo', 100, 143);  -- Calorías por 100g de huevo
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Banano', 100, 89);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Cebolla', 100, 40);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Aguacate', 100, 160);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Zanahoria', 100, 41);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Espinaca', 100, 23);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Brócoli', 100, 34);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Pescado', 100, 200);  -- Promedio para varios tipos de pescado
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Naranja', 100, 47);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Pera', 100, 57);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Fresa', 100, 32);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Kiwi', 100, 61);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Cereal', 100, 375);  -- Promedio para cereales azucarados
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Yogur', 100, 59);  -- Calorías para yogur natural
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Manteca', 100, 900);  -- Calorías para manteca de cerdo
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Aceite de oliva', 100, 884);  -- Calorías para aceite de oliva
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Almendra', 100, 576);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Cacahuate', 100, 567);  -- Calorías para cacahuetes
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Salmón', 100, 206);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Pechuga de pavo', 100, 120);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Atún', 100, 132);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Frambuesa', 100, 52);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Papaya', 100, 43);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Melón', 100, 34);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Uvas', 100, 69);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Pepino', 100, 16);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Champiñones', 100, 22);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Pepperoni', 100, 500);  -- Calorías por 100g de pepperoni
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Tocino', 100, 541);  -- Calorías por 100g de tocino
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Jamón', 100, 145);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Chía', 100, 486);  -- Calorías por 100g de semillas de chía
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Granola', 100, 471);  -- Calorías por 100g de granola
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Mango', 100, 60);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Piña', 100, 50);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Coco', 100, 354);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Habas', 100, 140);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Lentejas', 100, 116);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Garbanzos', 100, 164);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Arándano', 100, 57);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Acelga', 100, 19);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Albahaca', 100, 22);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Apio', 100, 16);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Menta', 100, 70);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Pimienta', 100, 251);  -- Calorías por 100g de pimienta
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Jengibre', 100, 80);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Lima', 100, 30);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Limón', 100, 29);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Cilantro', 100, 23);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Puerro', 100, 61);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Alcachofa', 100, 47);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Chirimoya', 100, 75);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Ciruela', 100, 46);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Granada', 100, 83);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Nuez', 100, 607);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Pistacho', 100, 562);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Castaña', 100, 213);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Pechuga de pollo', 100, 165);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Costillas', 100, 290);  -- Calorías por 100g de costillas
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Pizza', 100, 285);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Hamburguesa', 100, 250);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Sopa', 100, 50);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Pizza margarita', 100, 270);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Torta', 100, 200);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Croissant', 100, 406);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Galletas', 100, 492);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Té', 100, 2);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Café', 100, 2);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Chocolate', 100, 550);  -- Calorías por 100g de chocolate
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Pastel', 100, 350);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Quinoa', 100, 368);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Trigo sarraceno', 100, 343);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Tofu', 100, 144);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Edamame', 100, 121);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Tempeh', 100, 193);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Seitan', 100, 370);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Leche de almendra', 100, 17);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Leche de coco', 100, 230);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Leche de soja', 100, 54);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Pan integral', 100, 252);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Pan blanco', 100, 265);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Arándanos secos', 100, 325);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Ciruelas pasas', 100, 240);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Pasas', 100, 299);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Higos secos', 100, 249);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Almendra tostada', 100, 579);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Avellana', 100, 628);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Nuez pecana', 100, 691);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Semillas de girasol', 100, 584);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Semillas de calabaza', 100, 559);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Semillas de lino', 100, 534);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Semillas de amapola', 100, 525);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Espelta', 100, 338);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Avena', 100, 389);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Cebada', 100, 354);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Maíz', 100, 86);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Mijo', 100, 378);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Trigo', 100, 339);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Leche desnatada', 100, 35);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Helado de vainilla', 100, 207);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Helado de chocolate', 100, 216);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Queso cheddar', 100, 403);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Queso feta', 100, 264);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Queso parmesano', 100, 431);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Queso mozzarella', 100, 280);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Jamón serrano', 100, 241);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Chorizo', 100, 455);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Salchichón', 100, 411);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Filete de cerdo', 100, 242);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Costillas de cerdo', 100, 321);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Camarón', 100, 99);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Calamar', 100, 92);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Langosta', 100, 89);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Mejillones', 100, 86);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Ostras', 100, 68);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Caracoles', 100, 90);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Conejo', 100, 173);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Pato', 100, 337);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Mantequilla', 100, 717);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Crema de cacahuate', 100, 588);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Crema agria', 100, 193);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Mostaza', 100, 66);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Ketchup', 100, 112);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Mayonesa', 100, 680);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Tartar', 100, 207);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Puré de patatas', 100, 88);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Croquetas', 100, 120);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Empanada', 100, 250);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Muffin', 100, 305);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Brioche', 100, 364);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Pan de centeno', 100, 259);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Brownie', 100, 466);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Tarta de queso', 100, 321);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Bizcocho', 100, 275);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Cupcake', 100, 297);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Panqueque', 100, 227);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Churro', 100, 450);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Tarta de manzana', 100, 237);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Chocolate blanco', 100, 539);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Calabacín', 100, 17);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Berenjena', 100, 25);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Coliflor', 100, 25);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Rábanos', 100, 16);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Col rizada', 100, 50);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Remolacha', 100, 43);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Okra', 100, 33);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Hinojo', 100, 31);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Col de Bruselas', 100, 43);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Berro', 100, 11);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Rúcula', 100, 25);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Endivia', 100, 17);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Dátiles', 100, 277);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Mandarina', 100, 53);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Higo fresco', 100, 74);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Pomelo', 100, 42);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Granadilla', 100, 97);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Durazno', 100, 39);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Cereza', 100, 50);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Moras', 100, 43);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Fruta del dragón', 100, 60);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Lychee', 100, 66);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Acelgas rojas', 100, 19);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Ñame', 100, 118);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Rábano picante', 100, 48);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Ginseng', 100, 350);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Jícama', 100, 38);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Batata', 100, 86);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Taro', 100, 142);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Chayote', 100, 19);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Alga nori', 100, 35);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Wakame', 100, 45);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Kombu', 100, 60);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Caldo de hueso', 100, 15);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Queso cottage', 100, 98);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Queso ricotta', 100, 174);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Queso brie', 100, 334);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Ricino', 100, 98);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Pan sin gluten', 100, 245);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Tortilla de maíz', 100, 218);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Bagel integral', 100, 250);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Pan de centeno', 100, 260);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Tortitas de avena', 100, 200);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Chimichurri', 100, 270);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Pesto', 100, 303);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Gazpacho', 100, 44);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Hummus', 100, 166);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Tahini', 100, 595);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Paté', 100, 319);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Miso', 100, 198);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Col rizada', 100, 35);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Hinojo', 100, 31);
INSERT INTO alimento (nombre, cantidad, calorias) VALUES ('Rábano', 100, 16);